package sg.com.temasys.skylink.sdk.sampleapp.data.service;

import android.content.Context;
import android.os.Environment;
import android.util.Log;

import java.io.File;
import java.util.Date;

import sg.com.temasys.skylink.sdk.listener.FileTransferListener;
import sg.com.temasys.skylink.sdk.listener.LifeCycleListener;
import sg.com.temasys.skylink.sdk.listener.OsListener;
import sg.com.temasys.skylink.sdk.listener.RemotePeerListener;
import sg.com.temasys.skylink.sdk.rtc.Errors;
import sg.com.temasys.skylink.sdk.rtc.SkylinkConnection;
import sg.com.temasys.skylink.sdk.rtc.SkylinkException;
import sg.com.temasys.skylink.sdk.rtc.UserInfo;
import sg.com.temasys.skylink.sdk.sampleapp.ConfigFragment.Config;
import sg.com.temasys.skylink.sdk.sampleapp.utils.Utils;
import sg.com.temasys.skylink.sdk.sampleapp.data.model.PermRequesterInfor;
import sg.com.temasys.skylink.sdk.sampleapp.filetransfer.FileTransferContract;
import sg.com.temasys.skylink.sdk.sampleapp.utils.PermissionUtils;

import static sg.com.temasys.skylink.sdk.sampleapp.utils.Utils.toastLog;
import static sg.com.temasys.skylink.sdk.sampleapp.utils.Utils.toastLogLong;

/**
 * Created by muoi.pham on 20/07/18.
 */

public class FileTransferService extends SDKService implements FileTransferContract.Service, LifeCycleListener, FileTransferListener, OsListener, RemotePeerListener {

    private final String TAG = FileTransferService.class.getName();

    private Context mContext;

    //this variable need to be static for configuration change
    private static FileTransferContract.Presenter mPresenter;

    private SdkConnectionManager sdkConnectionManager;

    private PermissionUtils permissionUtils;

    //this variable need to be static for configuration change
    private static SkylinkConnection skylinkConnection;

    private String ROOM_NAME;
    private String MY_USER_NAME;

    private boolean isPeerJoined;

    private String fileNameDownloaded;

    public FileTransferService(Context mContext) {
        this.mContext = mContext;
        ROOM_NAME = Config.ROOM_NAME_FILE;
        MY_USER_NAME = Config.USER_NAME_FILE;
    }

    @Override
    public void setPresenter(FileTransferContract.Presenter presenter) {
        this.mPresenter = presenter;
    }

    //----------------------------------------------------------------------------------------------
    // FileTransferService implementation to work with SDK
    //----------------------------------------------------------------------------------------------

    public boolean isConnectingOrConnectedServiceHandler() {
        if (skylinkConnection != null) {
            return isConnectingOrConnectedBaseServiceHandler(skylinkConnection);
        }
        return false;
    }

    public void connectToRoomServiceHandler() {
        sdkConnectionManager = new SdkConnectionManager(mContext);
        skylinkConnection = sdkConnectionManager.initializeSkylinkConnectionForFileTransfer();

        setListeners();

        // Create the Skylink connection string.
        // In production, the connection string should be generated by an external entity
        // (such as a secure App server that has the Skylink App Key secret), and sent to the App.
        // This is to avoid keeping the App Key secret within the application, for better security.
        String skylinkConnectionString = Utils.getSkylinkConnectionString(
                ROOM_NAME, new Date(), SkylinkConnection.DEFAULT_DURATION);

        // The skylinkConnectionString should not be logged in production,
        // as it contains potentially sensitive information like the Skylink App Key ID.

        boolean connectFailed = !connectToRoomBaseServiceHandler(skylinkConnection, skylinkConnectionString, Config.USER_NAME_FILE);

        if (connectFailed) {
            String log = "Unable to connect to room!";
            toastLog(TAG, mContext, log);
            return;
        } else {
            String log = "Connecting...";
            toastLog(TAG, mContext, log);
        }
    }

    public void disconnectFromRoomServiceHandler() {
        if (skylinkConnection != null && isConnectingOrConnectedServiceHandler()) {
            disconnectFromRoomBaseServiceHandler(skylinkConnection);
        }
    }

    public String getRoomDetailsServiceHandler(boolean isPeerInRoom) {
        boolean isConnected = isConnectingOrConnectedServiceHandler();
        String roomName = getRoomNameBaseServiceHandler(skylinkConnection, Config.ROOM_NAME_FILE);
        String userName = getUserNameBaseServiceHandler(skylinkConnection, null, Config.USER_NAME_FILE);

        String roomDetails = "You are not connected to any room";

        if (isConnected) {
            roomDetails = "Now connected to Room named : " + roomName
                    + "\nYou are signed in as : " + userName + "\n";
            if (isPeerInRoom) {
                roomDetails += "Peer(s) are in the room";
            } else {
                roomDetails += "You are alone in this room";
            }
        }

        return roomDetails;

    }

    public void sendFileServiceHandler(String remotePeerId, String filePath) {
        // Check if valid file
        File file = new File(filePath);

        // Send request to peer requesting permission for file transfer
        try {
            sendFileTransferPermissionRequestBaseServiceHandler(skylinkConnection, remotePeerId, file.getName(), file.getAbsolutePath());

            String peer = "";
            if (remotePeerId == null) {
                peer = "all Peers in room";
            } else {
                peer = "Peer " + remotePeerId;
            }
            String log = "Sending file to " + peer + ".";
            toastLog(TAG, mContext, log);
        } catch (SkylinkException e) {
            String log = e.getMessage();
            toastLogLong(TAG, mContext, log);
            Log.e(TAG, log, e);
        }
    }

    private void onConnectUIChangeServiceHandler() {
        mPresenter.setRoomDetailsPresenterHandler(isPeerJoined);
        mPresenter.fillPeerRadioBtnPresenterHandler();
    }

    private int getNumRemotePeersServiceHandler() {
        int totalInRoom = getTotalInRoomServiceHandler();
        if (totalInRoom == 0) {
            return 0;
        }
        // The first Peer is the local Peer.
        return totalInRoom - 1;
    }

    private int getTotalInRoomServiceHandler() {
        String[] peerIdList = getPeerIdListBaseServiceHandler(skylinkConnection);

        if (peerIdList == null) {
            return 0;
        }
        // Size of array is number of Peers in room.
        return peerIdList.length;
    }

    private String getDownloadedFilePathServiceHandler() {
        File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        return path.getAbsolutePath() + File.separator + fileNameDownloaded;
    }


    //----------------------------------------------------------------------------------------------
    // Skylink Listeners
    //----------------------------------------------------------------------------------------------

    /**
     * Set listeners to receive callbacks when events are triggered.
     * SkylinkConnection instance must not be null or listeners cannot be set.
     * Do not set before {@link SkylinkConnection#init} as that will remove all existing Listeners.
     *
     * @return false if listeners could not be set.
     */
    private boolean setListeners() {
        if (skylinkConnection != null) {
            skylinkConnection.setLifeCycleListener(this);
            skylinkConnection.setRemotePeerListener(this);
            skylinkConnection.setOsListener(this);
            skylinkConnection.setFileTransferListener(this);
            return true;
        } else {
            return false;
        }
    }
    /***
     * Lifecycle Listener Callbacks -- triggered during events that happen during the SDK's
     * lifecycle
     */

    /**
     * Triggered if the connection is successful
     *
     * @param isSuccessful
     * @param message
     */

    @Override
    public void onConnect(boolean isSuccessful, String message) {
        //Update textview if connection is successful
        if (isSuccessful) {
            String log = "Connected to room " + ROOM_NAME + " (" + getRoomIdBaseServiceHandler(skylinkConnection) +
                    ") as " + getPeerIdBaseServiceHandler(skylinkConnection) + " (" + MY_USER_NAME + ").";
            toastLogLong(TAG, mContext, log);
            // [MultiParty]
            // Set the appropriate UI if already isConnected().
            onConnectUIChangeServiceHandler();

            //create PermissionUtils
            permissionUtils = new PermissionUtils(mContext);

        } else {
            String log = "Skylink failed to connect!\nReason : " + message;
            toastLogLong(TAG, mContext, log);
            mPresenter.setRoomDetailsPresenterHandler(isPeerJoined);
        }
    }

    @Override
    public void onDisconnect(int errorCode, String message) {
        // [MultiParty]
        // Reset peerList
        mPresenter.clearPeerListPresenterHandler();

        // Set the appropriate UI after disconnecting.
        onConnectUIChangeServiceHandler();
        String log = "[onDisconnect] ";
        if (errorCode == Errors.DISCONNECT_FROM_ROOM) {
            log += "We have successfully disconnected from the room.";
        } else if (errorCode == Errors.DISCONNECT_UNEXPECTED_ERROR) {
            log += "WARNING! We have been unexpectedly disconnected from the room!";
        }
        log += " Server message: " + message;
        toastLogLong(TAG, mContext, log);
    }

    @Override
    public void onLockRoomStatusChange(String remotePeerId, boolean lockStatus) {
        String log = "[SA] Peer " + remotePeerId + " changed Room locked status to "
                + lockStatus + ".";
        toastLog(TAG, mContext, log);
    }

    @Override
    public void onReceiveLog(int infoCode, String message) {
        Utils.handleSkylinkReceiveLog(infoCode, message, mContext, TAG);
    }

    @Override
    public void onWarning(int errorCode, String message) {
        Utils.handleSkylinkWarning(errorCode, message, mContext, TAG);
    }

    /**
     * File Transfer Listener Callbacks - triggered during events that happen during file transfer
     * between peers
     */

    @Override
    public void onFileTransferPermissionRequest(String peerId, String fileName, boolean isPrivate) {
        String log = "Received a file request";
        toastLogLong(TAG, mContext, log);
        // Take note of download file name.
        if (!"".equals(fileName)) {
            fileNameDownloaded = fileName;
        }
        //Send false to reject file transfer
        try {
            sendFileTransferPermissionResponseBaseServiceHandler(skylinkConnection, peerId, getDownloadedFilePathServiceHandler(), true);
        } catch (SkylinkException e) {
            log = e.getMessage();
            toastLogLong(TAG, mContext, log);
        }
    }

    @Override
    public void onFileTransferPermissionResponse(String peerId, String fileName, boolean
            isPermitted) {
        if (isPermitted) {
            String log = "Sending file";
            toastLog(TAG, mContext, log);
        } else {
            String log = "Sorry, the remote peer has not granted permission for file transfer";
            toastLog(TAG, mContext, log);
        }
    }

    public void onFileTransferDrop(String remotePeerId, String fileName, String message,
                                   boolean isExplicit) {
        String log = "The file transfer was dropped.\nReason : " + message;
        toastLogLong(TAG, mContext, log);
    }

    @Override
    public void onFileSendComplete(String remotePeerId, String fileName) {
        String log = "Your file has been sent";
        toastLog(TAG, mContext, log);
    }

    @Override
    public void onFileSendProgress(String remotePeerId, String fileName, double percentage) {
        String log = "Uploading... " + percentage;
        toastLog(TAG, mContext, log);
    }

    @Override
    public void onFileReceiveComplete(String remotePeerId, String fileName) {
        String log = "A file has been received : " + fileName;
        toastLog(TAG, mContext, log);

        String msg = "File Transfer Successful\n\nDestination : " + getDownloadedFilePathServiceHandler();

        mPresenter.onFileReceiveCompletePresenterHandler(msg);

    }

    @Override
    public void onFileReceiveProgress(String remotePeerId, String fileName, double percentage) {
        String log = "Downloading... " + percentage;
        toastLog(TAG, mContext, log);
    }


    /**
     * OsListener Callbacks - triggered by Android OS related events.
     */
    @Override
    public void onPermissionRequired(
            final String[] permissions, final int requestCode, final int infoCode) {
        PermRequesterInfor infor = new PermRequesterInfor(permissions, requestCode, infoCode);
        permissionUtils.onPermissionRequiredHandler(infor, TAG, mContext, mPresenter.getFragmentPresenterHandler());
    }

    @Override
    public void onPermissionGranted(String[] permissions, int requestCode, int infoCode) {
        Utils.onPermissionGrantedHandler(permissions, infoCode, TAG);
    }

    @Override
    public void onPermissionDenied(String[] permissions, int requestCode, int infoCode) {
        Utils.onPermissionDeniedHandler(infoCode, mContext, TAG);
    }

    /**
     * Remote Peer Listener Callbacks - triggered during events that happen when data or connection
     * with remote peer changes
     */

    public void onRemotePeerJoin(String remotePeerId, Object userData, boolean hasDataChannel) {
        // [MultiParty]
        //When remote peer joins room, keep track of user and update UI.
        // If Peer has no userData, use an empty string for nick.
        String nick = "";
        if (userData != null) {
            nick = userData.toString();
        }
        mPresenter.addPeerRadioBtnPresenterHandler(remotePeerId, nick);

        //Set room status if it's the only peer in the room.
        if (mPresenter.getPeerNumPresenterHandler() == 1) {
            isPeerJoined = true;
            // Update textview to show room status
            mPresenter.setRoomDetailsPresenterHandler(isPeerJoined);

            //set isPeerJoined value to view
            mPresenter.setIsPeerJoinedPresenterHandler(isPeerJoined);
        }
        String log = "Your Peer " + getPeerIdNickBaseServiceHandler(skylinkConnection, remotePeerId) + " connected.";
        toastLog(TAG, mContext, log);
    }

    @Override
    public void onRemotePeerLeave(String remotePeerId, String message, UserInfo userInfo) {
        // [MultiParty]
        // Remove the Peer.
        mPresenter.removePeerRadioBtnPresenterHandler(remotePeerId);

        //Set room status if there are no more peers.
        if (mPresenter.getPeerlistSizePresenterHandler() == 0) {
            isPeerJoined = false;
            // Update textview to show room status
            mPresenter.setRoomDetailsPresenterHandler(isPeerJoined);

            //set isPeerJoined value to view
            mPresenter.setIsPeerJoinedPresenterHandler(isPeerJoined);
        }

        int numRemotePeers = getNumRemotePeersServiceHandler();
        String log = "Your Peer " + getPeerIdNickBaseServiceHandler(skylinkConnection, remotePeerId, userInfo) + " left: " +
                message + ". " + numRemotePeers + " remote Peer(s) left in the room.";
        toastLog(TAG, mContext, log);
    }

    @Override
    public void onRemotePeerConnectionRefreshed(String remotePeerId, Object userData, boolean hasDataChannel, boolean wasIceRestarted) {
        String peer = "Skylink Media Relay server";
        if (remotePeerId != null) {
            peer = "Peer " + getPeerIdNickBaseServiceHandler(skylinkConnection, remotePeerId);
        }
        String log = "Your connection with " + peer + " has just been refreshed";
        if (wasIceRestarted) {
            log += ", with ICE restarted.";
        } else {
            log += ".\r\n";
        }

        toastLog(TAG, mContext, log);
    }

    @Override
    public void onRemotePeerUserDataReceive(String remotePeerId, Object userData) {
        // If Peer has no userData, use an empty string for nick.
        String nick = "";
        if (userData != null) {
            nick = userData.toString();
        }
        String log = "[SA][onRemotePeerUserDataReceive] Peer " + getPeerIdNickBaseServiceHandler(skylinkConnection, remotePeerId) +
                ":\n" + nick;
        toastLog(TAG, mContext, log);
    }

    @Override
    public void onOpenDataConnection(String s) {
        Log.d(TAG, "onOpenDataConnection");
    }

}
